### ISSUE TITLE
Simple answer 

### ISSUE THREAD

**Issue by lopter-sigyn** [staticapps/staticapps.org#17]
The language used on the static apps dot org site is written for an audience who probably can build their own hosting service just like you did.  You may wish to consider speaking simply to a new audience.

I asked your support to explain what a static app was (I am looking to become a new customer and maybe even refer more).  His answer wasn't really helpful but, as he explained - noobs are not our target audience.  Still, I feel like when you can't say something simply - it means you are compensating for something.  

Nonetheless, I found an answer I can understand and thought I'd share it with you.

One is Self-Sufficient (static), the other relies on Outside Data (dynamic)

Static applications are just that, static. They don't move. You can basically put them on a Smartphone or tablet and they will fully work without any internet or data connection. Think of these as simple tools, like a calculator or even some simple games, dictionary apps, or any type of app that just displays information and is only updated periodically through iTunes or Google Play Store. These work entirely within the file that is downloaded and installed on your users device.

On the other side of the coin are Dynamic Applications, these applications need to access a server in order to properly function, meaning they need a data connection either through WiFi or your phone's carrier. Think of these as weather applications, sports apps, many games, in fact, the vast majority of applications are dynamic in some sense. Whether they need to pull down images or videos in order to function properly, or need to access databases to provide real-time information.

**Comment by kevinchau** [comment]
Static apps can still rely on outside data. See AngularJS.
